
import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Head from "next/head";

import { MdAccountCircle } from 'react-icons/md';
import { useRouter } from 'next/router'; // For programmatic navigation

export default function dashboard({ Logout, user }) {
  const [dropdown, setDropdown] = useState(false);
  const [notification, setNotification] = useState(false); // State to track the notification
  const [firstName, setFirstName] = useState(null); // State to store the first name
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false); // State to control mobile menu
  const router = useRouter(); // Next.js router to navigate to /role

  useEffect(() => {
          if (!localStorage.getItem("token")) {
            router.push("/login");
          } else {
            const userFromStorage = JSON.parse(localStorage.getItem('user'));
              setFirstName(userFromStorage.fullName.split(" ")[0]);
          
          }
        }, []);

  const toggleDropdown = () => setDropdown(prev => !prev);
  const toggleMobileMenu = () => setMobileMenuOpen(prev => !prev);

  // Function to simulate storing an item in localStorage and triggering the notification
  const handleReportClick = () => {
    localStorage.removeItem("store"); // Remove notification from localStorage
    setNotification(false); // Hide the notification dot
  };

  return (
    <>
            <Head>
        <title>Shakktii मुलाखत प्रशिक्षक</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center"
        style={{ backgroundImage: "url('/bg.gif')" }}
      >
        {/* Navigation Bar */}
        <nav className="flex justify-between items-center mb-20 py-4 px-6 backdrop-blur-md bg-black/40 w-full rounded-xl shadow-lg">
          <div className="flex items-center gap-2">
            <img src="/Logo.png" alt="लोगो चिन्ह " className="w-8 h-8 object-contain" />
            <div className="text-white text-xl font-bold">Shakkti<span className="text-pink-500">AI</span></div>
          </div>
          
          {/* Desktop Navigation */}
          <ul className="hidden md:flex space-x-8 text-sm items-center">
            <li className="hover:text-pink-400 cursor-pointer transition-colors font-medium">होम</li>
            
            <Link href={'/progress'}>
              <li className="hover:text-pink-400 cursor-pointer transition-colors font-medium">
                <span className="relative inline-flex">
                  प्रोग्रेस
                  <span className="absolute -top-2 -right-2 bg-blue-500 text-white text-[10px] px-1.5 py-0.5 rounded-full">नवीन</span>
                </span>
              </li>
            </Link>
            
            <Link href={'/academicTest'}>
              <li className="hover:text-pink-400 cursor-pointer transition-colors font-medium">
                <span className="relative inline-flex">
                  शैक्षणिक परीक्षा
                  <span className="absolute -top-2 -right-2 bg-green-500 text-white text-[10px] px-1.5 py-0.5 rounded-full">नवीन</span>
                </span>
              </li>
            </Link>
            
            <Link href={'/oldreport'}>
              <li className="relative hover:text-pink-400 cursor-pointer transition-colors font-medium" onClick={handleReportClick}>
                अहवाल
                {notification && (
                  <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
                )}
              </li>
            </Link>
          </ul>
          
          {/* Desktop User Section */}
          <div className="hidden md:flex items-center gap-4">
            {user?.value ? (
              <div className="relative">
                <div className="flex items-center gap-2 cursor-pointer group" onClick={toggleDropdown}>
                  <MdAccountCircle className="text-2xl md:text-3xl text-white group-hover:text-pink-400 transition-colors" />
                  <span className="text-sm font-medium text-white group-hover:text-pink-400 transition-colors">
                    {firstName || 'Account'}
                  </span>
                </div>
                
                {dropdown && (
                  <div className="absolute right-0 shadow-xl top-12 rounded-lg w-48 border border-gray-200 bg-white text-black overflow-hidden z-50">
                    <ul>
                      <Link href={'/profile'}>
                        <li className="hover:text-blue-700 text-sm font-medium p-3 cursor-pointer border-b border-gray-100 hover:bg-gray-50 transition-colors flex items-center gap-2">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                          </svg>
                          प्रोफाइल
                        </li>
                      </Link>
                      <Link href={'/progress'}>
                        <li className="hover:text-blue-700 text-sm font-medium p-3 cursor-pointer border-b border-gray-100 hover:bg-gray-50 transition-colors flex items-center gap-2">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z" clipRule="evenodd" />
                          </svg>
                          माझी प्रगती
                        </li>
                      </Link>
                      
                      <li onClick={Logout} className="hover:text-red-700 text-sm font-medium p-3 cursor-pointer hover:bg-gray-50 transition-colors flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                          <path fillRule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V7.414l-5-5H3zm7 5a1 1 0 00-1 1v5.586l-1.293-1.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 15.586V9a1 1 0 00-1-1z" clipRule="evenodd" />
                        </svg>
                        बाहेर पडा
                      </li>
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <Link href="/login">
                <button className="px-4 py-2 bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-full hover:from-pink-600 hover:to-purple-700 transition duration-300 shadow-lg hover:shadow-xl font-medium">
                  लॉगिन
                </button>
              </Link>
            )}
          </div>
          
          {/* Mobile Menu Button - Single hamburger icon for mobile */}
          <button 
            className="md:hidden text-white focus:outline-none z-20" 
            onClick={toggleMobileMenu}
          >
            {mobileMenuOpen ? (
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            ) : (
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16m-7 6h7" />
              </svg>
            )}
          </button>
          
          {/* Mobile Navigation - Combining all navigation elements for mobile */}
          {mobileMenuOpen && (
            <div className="md:hidden fixed inset-0 bg-black bg-opacity-80 z-10 flex flex-col items-center justify-center">
              <ul className="flex flex-col space-y-6 text-center items-center">
                <li className="text-white hover:text-pink-400 font-medium text-xl cursor-pointer" onClick={toggleMobileMenu}>होम</li>
                
                <Link href={'/progress'}>
                  <li className="text-white hover:text-pink-400 font-medium text-xl cursor-pointer" onClick={toggleMobileMenu}>
                    <span className="relative inline-flex">
                      प्रोग्रेस
                      <span className="absolute -top-2 -right-2 bg-blue-500 text-white text-[10px] px-1.5 py-0.5 rounded-full"> नवीन</span>
                    </span>
                  </li>
                </Link>
                
                <Link href={'/oldreport'}>
                  <li className="text-white hover:text-pink-400 font-medium text-xl cursor-pointer relative" onClick={() => { handleReportClick(); toggleMobileMenu(); }}>
                    अहवाल
                    {notification && (
                      <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
                    )}
                  </li>
                </Link>
                
                {user?.value ? (
                  <>
                    <Link href={'/profile'}>
                      <li className="text-white hover:text-pink-400 font-medium text-xl cursor-pointer" onClick={toggleMobileMenu}>
                        प्रोफाइल
                      </li>
                    </Link>
                    <li className="text-white hover:text-red-400 font-medium text-xl cursor-pointer" onClick={() => { Logout(); toggleMobileMenu(); }}>
                      बाहेर पडा
                    </li>
                  </>
                ) : (
                  <Link href="/login">
                    <li className="text-white hover:text-pink-400 font-medium text-xl cursor-pointer bg-gradient-to-r from-pink-500 to-purple-600 px-6 py-2 rounded-full" onClick={toggleMobileMenu}>
                      लॉगिन
                    </li>
                  </Link>
                )}
              </ul>
            </div>
          )}
        </nav>

        {/* Main Content */}
        <div className="flex flex-col items-center   text-center w-full">
          <div className="w-20 h-20  border-2 border-white rounded-full flex items-center justify-center">
            <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
          </div>

          

          {/* Hero Section */}
          <div className="relative mb-10 flex flex-col md:flex-row items-center justify-center text-white max-w-7xl mx-auto">
            <div className="text-center md:text-left max-w-2xl md:mr-32 order-2 md:order-1 z-10">
              <div className="flex flex-col gap-3">
                <span className="inline-block bg-gradient-to-r from-pink-500 to-purple-600 text-white px-4 py-1 rounded-full text-sm font-medium mb-2 w-fit animate-pulse">
                  नवीन: प्रोग्रेस ट्रॅकिंग आणि विश्लेषण
                </span>
                
                <h1 className="text-4xl md:text-6xl font-bold leading-tight text-white">
                  तुमच्या <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-purple-600">मुलाखत कौशल्यांवर </span>प्रभुत्व मिळवा
                  <br />
                  एआय-आधारित फीडबॅकसह
                </h1>
                
                <p className="text-gray-300 text-lg mt-2">
                  आमच्या एआय मुलाखतकर्त्यासोबत सराव करा, त्वरित फीडबॅक मिळवा आणि सविस्तर विश्लेषणाच्या आधारे वेळोवेळी आपली प्रोग्रेस ट्रॅक करा.
                </p>
                
                <div className="mt-6 flex flex-col sm:flex-row gap-4">
                  <Link href={'/role'}>
                    <button className="bg-gradient-to-r from-pink-500 to-purple-600 text-white py-3 px-8 rounded-full text-lg font-semibold hover:from-pink-600 hover:to-purple-700 transition duration-300 shadow-lg hover:shadow-xl flex items-center gap-2 group">
                      सराव सुरू करा
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 group-hover:translate-x-1 transition-transform" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clipRule="evenodd" />
                      </svg>
                    </button>
                  </Link>
                  
                  
                  <Link href={'/progress'}>
                    <button className="border-2 border-white hover:border-pink-400 text-white py-3 px-8 rounded-full text-lg font-semibold hover:text-pink-400 transition duration-300 flex items-center gap-2 group">
                      प्रोग्रेस पाहण्यासाठी क्लिक करा
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 group-hover:translate-x-1 transition-transform" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v3.586L7.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 10.586V7z" clipRule="evenodd" />
                      </svg>
                    </button>
                  </Link>
                  
                  <Link href={'/practices'}>
                    <button className="bg-gradient-to-r from-indigo-500 to-blue-600 text-white py-3 px-8 rounded-full text-lg font-semibold hover:from-indigo-600 hover:to-blue-700 transition duration-300 shadow-lg hover:shadow-xl flex items-center gap-2 group">
                      प्रॅक्टिस टेस्ट्स
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 group-hover:translate-x-1 transition-transform" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                        <path fillRule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clipRule="evenodd" />
                      </svg>
                    </button>
                  </Link>
                  
                  
                 


                </div>
              </div>
            </div>
            
            <div className="order-1 md:order-2 mb-8 md:mb-0">
              <div className="relative">
                <img 
                  src="/mock.png" 
                  alt="एआय मुलाखत सहाय्यक" 
                  className="relative w-full max-w-md md:max-w-xl rounded-lg" 
                />
              </div>
            </div>
          </div>
          


        </div>
      </div>

      <div className="text-gray-900 p-8 py-20 min-h-screen bg-cover" style={{ backgroundImage: "url('/whitebg.jpg')" }}>
        <div className="max-w-7xl mx-auto">
          <h1 className="text-4xl font-bold text-center mb-12">
            तुम्ही मुलाखतीसाठी तयार आहात का? <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-purple-600">Shakkti AI</span> सोबत चाचणी देऊन तपासा.
          </h1>
          
          {/* Feature Sections */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10 mb-24">
            {/* Progress Tracking Feature */}
            <div className="bg-gradient-to-br from-blue-50 to-purple-50 p-8 rounded-2xl shadow-lg">
              <div className="flex flex-col items-center md:items-start gap-6">
                <div className="inline-block bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-medium">
                  मुलाखत विश्लेषण
                </div>
                <h2 className="text-2xl font-bold text-gray-800 text-center md:text-left">तुमची मुलाखत प्रोग्रेस ट्रॅक करा</h2>
                <p className="text-gray-600">
                  आमच्या प्रोग्रेस ट्रॅकिंग सिस्टममुळे तुम्हाला वेळोवेळी तुमच्या कामगिरीतील सुधारणा पाहता येतात. विविध कौशल्यांतील कामगिरीचे सविस्तर विश्लेषण करा आणि सुधारणा करावयाचे भाग ठरवा.
                </p>
                <ul className="space-y-2">
                  {['कौशल्य विश्लेषण', 'परफॉर्मन्स कम्पेरिजन', 'ग्रोथ व्हिज्युअलायझेशन', 'मुलाखतींचा आढावा'].map((feature, index) => (
                    <li key={index} className="flex items-center gap-2">
                      <svg className="h-5 w-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
                <Link href="/progress">
                  <button className="bg-gradient-to-r from-blue-500 to-purple-600 text-white py-2 px-6 rounded-lg font-medium hover:from-blue-600 hover:to-purple-700 transition duration-300 shadow-md mt-2">
                    प्रोग्रेस पहा
                  </button>
                </Link>
              </div>
            </div>

            {/* Practice Tests Feature */}
            <div className="bg-gradient-to-br from-indigo-50 to-cyan-50 p-8 rounded-2xl shadow-lg">
              <div className="flex flex-col items-center md:items-start gap-6">
                <div className="inline-block bg-indigo-100 text-indigo-800 px-3 py-1 rounded-full text-sm font-medium">
                  नवीन फिचर
                </div>
                <h2 className="text-2xl font-bold text-gray-800 text-center md:text-left">प्रॅक्टिस टेस्ट्स आणि असेसमेंट्स</h2>
                <p className="text-gray-600">
                  आमच्या विशेष अभ्यास चाचण्यांसह तुमची भाषा आणि मुलाखत कौशल्ये सुधारा. तुमच्या बोलण्याच्या, ऐकण्याच्या, वाचनाच्या आणि लेखनाच्या क्षमतांना सुधारण्यासाठी वैयक्तिक AI फीडबॅक मिळवा.
                </p>
                <ul className="space-y-2">
                  {['पर्सनालिटी असेसमेंट', 'बोलण्याचा सराव', 'ऐकण्याची समज', 'वाचन आणि लेखन चाचण्या'].map((feature, index) => (
                    <li key={index} className="flex items-center gap-2">
                      <svg className="h-5 w-5 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
                <Link href="/practices">
                  <button className="bg-gradient-to-r from-indigo-500 to-blue-600 text-white py-2 px-6 rounded-lg font-medium hover:from-indigo-600 hover:to-blue-700 transition duration-300 shadow-md mt-2">
                    प्रॅक्टिस टेस्ट्स सुरू करा
                  </button>
                </Link>
              </div>
            </div>
            
            {/* Academic Test Feature - NEW */}
            <div className="bg-gradient-to-br from-green-50 to-teal-50 p-8 rounded-2xl shadow-lg">
              <div className="flex flex-col items-center md:items-start gap-6">
                <div className="inline-block bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">
                  नवीन लाँच!
                </div>
                <h2 className="text-2xl font-bold text-gray-800 text-center md:text-left">वैयक्तिकृत शैक्षणिक चाचण्या</h2>
                <p className="text-gray-600">
                 तुमच्या स्ट्रीम, डिपार्टमेंट, आणि विषयासाठी खास तयार केलेल्या शैक्षणिक टेस्ट्स द्या. तत्काळ AI-आधारित मूल्यांकन आणि सविस्तर फीडबॅक मिळवा, ज्यामुळे तुमची शैक्षणिक कार्यक्षमता सुधारेल.</p>
                <ul className="space-y-2">
                  {['विषयानुसार प्रश्न', 'विविध टेस्ट फॉर्मॅट्स (MCQ, लेखी, बोलणी)', 'अवघडपणानुसार समायोजन', '३-स्टार रेटिंग पद्धत'].map((feature, index) => (
                    <li key={index} className="flex items-center gap-2">
                      <svg className="h-5 w-5 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
                <Link href="/academicTest">
                  <button className="bg-gradient-to-r from-green-500 to-teal-600 text-white py-2 px-6 rounded-lg font-medium hover:from-green-600 hover:to-teal-700 transition duration-300 shadow-md mt-2">
                    शैक्षणिक टेस्ट द्या
                  </button>
                </Link>
              </div>
            </div>
          </div>


        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg gap-10"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p1.jpeg"
              width={300}

              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 shadow-2xl shadow-gray-300"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">1</span>
              <h2 className="text-xl font-semibold text-purple-700">प्रॅक्टिस करा</h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
             तुमच्या मुलाखतीच्या कौशल्यांचा अभ्यास करा, सुधारणा आवश्यक असलेले भाग ओळखा आणि उत्तरे अधिक प्रभावी बनवा. वास्तविक मुलाखतीपूर्वी आत्मविश्वास वाढवा आणि तणाव कमी करा, जेणेकरून तुम्ही यशस्वी होऊ शकता.
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg mr-10  sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p2.jpeg"
              width={300}
              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 lg:ml-32 shadow-2xl order-1 shadow-gray-300"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">2</span>
              <h2 className="text-xl font-semibold text-purple-700">AI आधारित थेट मुलाखत सराव सत्र</h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              AI-सह थेट मॉक इंटरव्ह्यूचा अनुभव घ्या – जिथे तुमच्या बोलण्याची शैली, आत्मविश्वास आणि अचूकतेवर त्वरित प्रतिक्रिया मिळते. डेटा-आधारित विश्लेषणामुळे वेळ वाचतो आणि सुधारण्याच्या दिशा स्पष्ट होतात.
            </p>
          </div>
        </div>




        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p3.jpg"
              width={300}

              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 shadow-2xl shadow-gray-700"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">3</span>
              <h2 className="text-xl font-semibold text-purple-700">तुमच्या सोयीनुसार मुलाखतीचे वेळापत्रक</h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
             कधीही आणि कुठेही सराव करा – निश्चित वेळापत्रकाची गरज नाही. विद्यार्थ्यांना आणि व्यावसायिकांना तत्काळ प्रवेश मिळावा यासाठी फ्लेक्सिबल आणि स्ट्रेस-फ्री तयारीची सुविधा.
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg lg:ml-32 mr-10 sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p4.png"
              width={300}
              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 shadow-2xl order-1 shadow-gray-800"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">4</span>
              <h2 className="text-xl font-semibold text-purple-700">शिक्षणात गेमसारखा अनुभव</h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              MockMingle मध्ये स्कोर्स, बॅजेस आणि लीडरबोर्ड्ससह गैमीकरण वापरून शिकणे मजेदार, प्रेरणादायक आणि फलदायी बनवले आहे, तसेच तुमच्या प्रगतीवर लक्ष ठेवले जाते.
            </p>
          </div>
        </div>

        <div className="relative mt-10 lg:m-40 grid grid-cols-1 lg:grid-cols-2 " style={{ perspective: "1000px" }}>
          <div
            className="transform rounded-lg"
            style={{
              transform: "rotateY(50deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p5.png"
              width={300}

              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 shadow-2xl shadow-gray-700"
            />
          </div>

          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">5</span>
              <h2 className="text-xl font-semibold text-purple-700"> तज्ज्ञांकडून फीडबॅक मिळवा</h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              AI आणि इंडस्ट्री तज्ज्ञांकडून संवाद, तांत्रिक कौशल्ये आणि कामगिरी यावर सखोल फीडबॅक मिळवा, तसेच तुमच्या मुलाखतीतील यशासाठी वैयक्तिक सुधारणा सूचना प्राप्त करा.
            </p>
          </div>
        </div>


        <div
          className="relative lg:m-40 mt-10 grid grid-cols-1 lg:grid-cols-2"
          style={{ perspective: "1000px" }}
        >
          {/* Image Section */}
          <div
            className="transform rounded-lg mr-10 lg:ml-32 sm:order-first lg:order-last"
            style={{
              transform: "rotateY(330deg)",
              transformStyle: "preserve-3d",
            }}
          >
            <img
              src="/p6.jpg"
              width={300}
              alt="तयारी हाच यशाचा मार्ग आहे।"
              className="rounded-lg h-40 shadow-2xl order-1 shadow-gray-800"
            />
          </div>

          {/* Text Section */}
          <div className="mt-4">
            <div className="flex items-center gap-2">
              <span className="bg-purple-500 text-white px-3 py-1 rounded-full text-sm">6</span>
              <h2 className="text-xl font-semibold text-purple-700">व्हिडिओ स्वरूपात मार्गदर्शन मिळवा
              </h2>
            </div>
            <p className="text-gray-600 mt-2 text-sm leading-relaxed">
              AI आणि तज्ज्ञांच्या मदतीने तुम्हाला व्हिडिओ स्वरूपात मार्गदर्शन मिळेल, ज्यात उत्तर देण्याच्या पद्धती, शारीरिक भाषा आणि आवाजावर सखोल सूचना दिल्या जातील. यामुळे तुम्हाला सुधारणा सहज आणि आकर्षकपणे करता येईल.
            </p>
          </div>
        </div>


        </div>
      </div>
      <div className="relative bg-blue-950 grid grid-cols-1 lg:grid-cols-2">
        <div className="">
          <img src="/footermock.png" className="" />
        </div>
        <div className="text-center mt-5">
          <h2 className="text-gray-300 text-2xl">संपर्क करा</h2>
          <h2 className="text-gray-300 text-3xl mt-2 font-bold">info@shakktii.in</h2>
          <div>
          </div>
        </div>
      </div>
    </>
  );
}