


// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import { getApiResponse } from './api/response';
// import Link from "next/link";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage

//   useEffect(() => {
//     // Request microphone (audio) access
//     const requestPermissions = async () => {
//       try {
//         // Requesting audio permission (microphone)
//         await navigator.mediaDevices.getUserMedia({ audio: true, sound: true });
//         console.log("Microphone and sound access granted.");
//       } catch (err) {
//         console.error("Microphone and sound access denied:", err);
//         // Optionally, show an alert or message to the user about the permission issue
//       }
//     };

//     requestPermissions();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, []);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (<><Head>
//     <title>Shakktii Interview Trainer</title>
//     <meta name="description" content="Generated by create next app" />
//     <meta name="viewport" content="width=device-width, initial-scale=1" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//     <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//       {/* Navigation Bar */}
//       <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//         <div className="text-white text-lg font-bold">Shaktti AI</div>
//         <ul className="flex space-x-6 text-sm">
//           <li className="hover:text-purple-400 cursor-pointer">Home</li>
//           <Link href={'/oldreport'}>
//             <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//               Reports
//               {/* Show the notification red dot if true */}
//               {notification && (
//                 <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//               )}
//             </li>
//           </Link>
//           <div className="relative">
//             {/* User Dropdown */}
//             {user?.value && (
//               <div className="relative">
//                 <MdAccountCircle
//                   className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                   onClick={toggleDropdown} // Toggle on click
//                 />
//                 {dropdown && (
//                   <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                     <ul>
//                       {/* Profile Link */}
//                       <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                         Profile
//                       </li></Link>
//                       {/* Logout Link */}
//                       <li
//                         onClick={Logout}
//                         className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                       >
//                         Logout
//                       </li>
//                     </ul>
//                   </div>
//                 )}
//               </div>
//             )}

//             {/* Login button for guests */}
//             {!user?.value && (
//               <Link href="/login">
//                 <div className="ml-4">
//                   <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                     Login
//                   </button>
//                 </div>
//               </Link>
//             )}
//           </div>
//         </ul>
//       </nav>

//       {/* Header Section */}
//       <div className="flex flex-col items-center text-center">
//         {/* Logo */}
//         <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//           <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//         </div>

//         <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//         <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//         {/* Image Section */}
//         <div className="flex justify-center mt-4 mb-4">
//           <img
//             src="/home.png"
//             alt="Job Interview"
//             className="max-w-sm w-full h-auto object-contain"
//           />
//         </div>

//         {/* Description */}
//         <p className="text-center text-gray-300 max-w-lg mx-auto">
//           Landing your dream job starts with a great interview. We provide expert tips, real-world
//           insights, and proven strategies to help you impress employers and stand out from the
//           competition.
//         </p>

//         {/* List of Services */}
//         <ul className="mt-4 text-center space-y-2 text-gray-200">
//           <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//           <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//           <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//         </ul>

//         {/* Call to Action Button */}
//         <div className="mt-6 flex justify-center pb-10">
//           <Link href={'/role'}>
//             <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//               GET STARTED
//             </button>
//           </Link>
//         </div>
//       </div>
//     </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = false;
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   // Start the speech recognition when the component mounts or when the user clicks a button
//   const startRecognition = () => {
//     if (recognition.current) {
//       recognition.current.start(); // Start listening to the user's speech
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Call to Action Button */}
//           <div className="mt-6 flex justify-center pb-10">
//             {/* Replacing the button with speech recognition trigger */}
//             {!speechRecognizing && (
//               <button
//                 onClick={startRecognition}
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"
//               >
//                 Speak "I am ready" to Get Started
//               </button>
//             )}
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           if(!recognition.current.onstart){

//         }
//           // You can try to restart recognition only if it's completely ended.
//           // No need to call start() here if it's already restarted before
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



// //perfect
// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation



// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English


//     window.speechSynthesis.speak(utterance);
//   };



// // console.log("this is User",user);


// useEffect(() => {
//   const userFromStorage = JSON.parse(localStorage.getItem('user'));

//   // console.log(userFromStorage);
//   setUserr(userFromStorage);

//   // No need to speak until the user is set
//   if (userFromStorage) {
//     // Speak the instructions once user data is loaded
//     const firstName = userFromStorage?.fullName?.split(' ')[0];
//     speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//   }
// }, []); // Only runs once when the component is mounted


//   useEffect(() => {
//     // Initialize Speech Recognition API

//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>

//         </div>
//       </div>
//     </>
//   );
// }



// import { useState, useEffect, useRef } from "react";
// import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//         speak('Hi, I am Shakti, your interview trainer! Tap the screen to continue.');
//       } else {
//         speak('Hi, I am Shakti, your interview trainer! When you are ready, then speak the phrase "I am ready."');
//       }
//     }, 5000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, []);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div style={{ height: '100vh' }}>
//       <OwlModel />
//     </div>
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//           Speak OR Click On Get Started
//           <div className="mt-6 flex justify-center pb-10">
//             <Link href={'/role'}>
//               <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                 GET STARTED
//               </button>
//             </Link>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// // import OwlModel from '../components/OwlModel'
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role
//   const recognition = useRef(null); // Reference to the speech recognition instance
//   const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing
//   const [isIphone, setIsIphone] = useState(false); // State to track if the device is iPhone
// const[userr, setUserr] = useState(null);

//   const speak = (text) => {
//     const utterance = new SpeechSynthesisUtterance(text);
//     utterance.lang = 'en-US'; // Set language to English
//     window.speechSynthesis.speak(utterance);
//   };

//   useEffect(() => {
//     // Detect if the device is iPhone
//     if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
//       setIsIphone(true);
//     }



//     // Delay speech synthesis for 1 second after page load
//     const timeoutId = setTimeout(() => {
//       // Check if the device is iOS and adjust the speech message accordingly
//       if (isIphone) {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           }
//       } else {
//         const userFromStorage = JSON.parse(localStorage.getItem('user'));

//           // console.log(userFromStorage);
//           setUserr(userFromStorage);

//           // No need to speak until the user is set
//           if (userFromStorage) {
//             // Speak the instructions once user data is loaded
//             const firstName = userFromStorage?.fullName?.split(' ')[0];
//             speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`);
//           } }
//     }, 1000); // Delay by 1 second after page load

//     return () => clearTimeout(timeoutId); // Cleanup timeout on component unmount
//   }, [isIphone]);

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setIsRecognizing(true); // Set the recognizing flag to true
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setIsRecognizing(false); // Set the recognizing flag to false

//           // Restart recognition only if it's fully ended and not already recognizing
//           if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
//             console.log("Speech recognition restarted."); // Debug log
//             recognition.current.start(); // Restart recognition
//           }
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           // If the user says "I am ready", navigate to /role
//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads if it's not already started
//         if (recognition.current && !isRecognizing) {
//           recognition.current.start();
//         }
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router, isRecognizing]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shakkti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle className="text-2xl md:text-3xl mx-2 cursor-pointer" onClick={toggleDropdown} />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         <Link href={'/profile'}>
//                           <li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Profile</li>
//                         </Link>
//                         <li onClick={Logout} className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">Logout</li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">Login</button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* <div style={{ height: '100vh' }}>
//             <OwlModel  />
//           </div> */}
//           <div  className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>
//           {isIphone && (
//           <>
//           <div onClick={() => speak(`Hey ${firstName}, welcome back! Just say 'I'm ready' when you're all set!`)}>
//           <h1  className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2  className="text-3xl font-bold text-pink-500">Interview</h2>
//           </div> </>
//          )}
//           {!isIphone && (
//           <>
//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>
//           </>
//          )}
//           <div className="flex justify-center mt-4 mb-4">
//             <img src="/home.png" alt="Job Interview" className="max-w-sm w-full h-auto object-contain" />
//           </div>

//           <p   className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world insights, and proven strategies to help you impress employers and stand out from the competition.
//           </p>

//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>

//           {/* Only show the button for iPhone users */}
//           {isIphone && (
//             <div className="mt-6 flex justify-center pb-10">
//               <button
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"

//               >
//                 TAP TO CONTINUE
//               </button>
//             </div>
//           )}

//           {/* GET STARTED button */}

//             <div className="mt-6 flex justify-center pb-10">
//               <Link href={'/role'}>
//                 <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//                   GET STARTED
//                 </button>
//               </Link>
//             </div>

//         </div>
//       </div>
//     </>
//   );
// }


import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router'; // For programmatic navigation

export default function Home() {
  const [selected, setSelected] = useState(null);
  const plans = [
    { title: '8th to 12th', price: 99 },
    { title: 'Graduate', price: 99 },
    { title: 'Post Graduate', price: 99 },
    { title: 'Competitive', price: 99 },
    { title: 'Professional', price: 99 },
  ];
  const features = [
    "5 Mock Interviews",
    "✅ Interview Reports",
    "✅ Chat Support (+Rs 99)",
    "✅ YouTube Video Suggestions",
    "✅ Detailed Score Progress",
    "✅ Performance Analysis",
    "✅ Score by Job Role",
    "✅ Comparison Interviews",
    "✅ Detailed Analysis",
    "✅ Test 20 (Personality & Academic Test)",
  ];
  return (
    <>
      <Head>
        <title>Shakktii Interview Trainer</title>
        <meta name="description" content="Empower your learning journey through skill analysis, real-time chats, and gamified challenges to prepare for mock interviews — with MockMingle" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen  bg-black px-4 bg-cover flex flex-col items-center justify-center overflow-x-hidden sm:overflow-x-hidden">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 min-h-screen border-black justify-center">

          {/* Image section */}
          <div className="min-h-screen flex justify-center items-center order-1 lg:order-2">
            <div className="w-[25rem] aspect-square rounded-full   shadow-[0_0_5px_5px_rgba(255,255,255,0.5)] flex justify-center items-center">
              <div className="w-[18rem] aspect-square rounded-full   shadow-[inset_0_0_10px_rgba(255,255,255,0.5)] flex justify-center items-center">
                <div className="w-[12rem] aspect-square rounded-full   shadow-[0_0_5px_5px_rgba(255,255,255,0.5)] flex justify-center items-center">
                  <Image src="/SVG_mascote.svg" alt="logo" className="absolute -mr-6 -mt-10" width={750} height={650} />
                </div>
              </div>
            </div>
          </div>

          {/* Text content section */}
          <div className="col-span-1 lg:col-span-2 mt-20 order-2 lg:order-1 flex flex-col items-center ">
            <h1 className="text-4xl m-10 font-bold text-shadow-lg text-white" >Your Journey from Learning to Leading Starts Here</h1>
            <p className="text-2xl m-10 font-semibold text-shadow- text-[#5E3A66] " >Empower your learning journey through skill analysis, real-time chats, and gamified challenges to prepare for mock interviews — with&nbsp;MockMingle</p>
            <div className="flex justify-center rounded-full  w-full">
              <button className="shadow-[0px_0px_5px_5px_rgba(0,0,0,0.10)]  w-[42rem]  text-black py-3 px-6 rounded-full text-lg font-semibold bg-white hover:bg-pink-600 hover:text-white transition duration-300">
                Get Started
              </button>
            </div>
          </div>
        </div>
      </div>


      <div className="overflow-x-hidden mt-16 w-full rounded-t-[6.188rem] shadow-[0_0_5px_5px_rgba(0,0,0,0.10)] bg-gradient-to-t from-[#76626A] via-[#AE98B3] to-[#D9C0CB] px-4 sm:px-10 py-10">
        {/* Heading */}
        <h1
          className="text-2xl lg:text-4xl font-bold text-left py-4 text-black"
          style={{
            fontFamily: "Arial, sans-serif",
            backgroundColor: "#9A6192",
            // color: "transparent",
            textShadow: "2px 2px 3px rgba(255, 255, 255, 0.5)",
            WebkitBackgroundClip: "text",
            backgroundClip: "text",
          }}
        >
          Why MockMingle?
        </h1>

        <h1
          className="text-base lg:text-2xl font-bold text-left py-4 text-black"
          style={{
            fontFamily: "Arial, sans-serif",
            backgroundColor: "#363232",
            // color: "transparent",
            textShadow: "2px 2px 3px rgba(255, 255, 255, 0.5)",
            WebkitBackgroundClip: "text",
            backgroundClip: "text",
          }}
        >
          Because we believe skill development should be fun, personalized, and results-driven — helping you move from practice to perfection with confidence!
        </h1>

        {/* Cards */}
        <div className="grid  grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-52   mt-20">
          {/* Card 1 */}
          <div>
            <div className="flex  mt-28 justify-center items-center flex-col bg-gradient-to-t from-[#000000] to-[#D4D4D4] rounded-t-lg p-4">
              <div className="relative -mt-28 w-48 h-48 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                <div className="w-40 h-40 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                  <div className="w-32 h-32 flex items-center justify-center bg-[#9d77a6] rounded-full shadow-inner">
                    <div className="w-32 h-32 flex items-center justify-center bg-[#9d77a6] rounded-full shadow-inner">
                      <Image src="/skill1.svg" alt="Skill" width={64} height={64} className=" min-w-[55rem] min-h-[55rem] ml-[24.3rem] mt-[14.5rem]" />
                    </div>

                  </div>
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white mt-10  " style={{
                  fontFamily: "Arial, sans-serif",
                  textShadow: "2px 2px 3px rgba(255, 255, 255, 0.5)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                }}>Skill</h1>
              </div>
              <div className="mt-10 mr-14 ">
                <div className="absolute mt-3 ml-2 w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[1.05rem]">01</h2>
              </div>

            </div>
            <div className="bg-[#000000BA]">

              <h1 className="text-xl font-light text-white text-center pt-10">Skill Gap Analysis</h1>
              <p className="text-left lg:m-4 text-white text-sm">Understand exactly where you stand.
                MockMingle conducts comprehensive skill assessments designed for both students and working professionals.
                You’ll receive personalized reports highlighting your strengths and skill gaps, helping you focus on the areas that matter the most for your career growth.
              </p>
              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10rem] xl:ml-[6.5rem]  ml-[10.8rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[11.3rem] 2xl:ml-[10.5rem] xl:ml-[7rem]">02</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">Community Forums and Discussion Rooms</h1>
                <p className="text-left lg:m-4 text-white text-sm">You’re never alone in your journey at MockMingle!
                  Join topic-specific forums and discussion rooms where you can talk, learn, and share knowledge with like-minded peers, career mentors, and HR experts.
                  Engage in debates, peer reviews, Q&A sessions, and mock group discussions.</p>
              </div>

              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10.5rem] xl:ml-[6.5rem]  ml-[10.8rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[11.3rem] 2xl:ml-[11rem] xl:ml-[7rem]">03</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">Interview Room</h1>
                <p className="text-left lg:m-4 text-white pb-16 text-sm">Step into a live virtual Interview Room anytime.
                  Whether practicing solo or with an interviewer, experience real-time pressure, instant question generation, and situational-based role-play interviews.
                  Practice often, and beat interview anxiety before the real day arrives!</p>
              </div>


            </div>

          </div>



          {/* Card 2 */}
          <div>
            <div className="flex mt-28  justify-center flex-col bg-gradient-to-t from-[#000000] to-[#D4D4D4] rounded-t-lg p-4">
              <div className="relative m-auto  -mt-28 w-48 h-48 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                <div className="w-40 h-40 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                  <div className="w-32 h-32 flex items-center justify-center bg-[#9d77a6] rounded-full shadow-inner">
                    <Image src="/learning.svg" alt="Skill" width={64} height={64} className=" min-w-[55rem] min-h-[55rem] -ml-[1rem] mt-[7.9rem]" />
                  </div>
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white mt-10 text-center " style={{
                  fontFamily: "Arial, sans-serif",
                  textShadow: "2px 2px 3px rgba(255, 255, 255, 0.5)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                }}>Learning</h1>
              </div>
              <div className="mt-10 mr-14">
                <div className="absolute mt-3 ml-[9.5rem] 2xl:ml-[9.2rem]  xl:ml-[6rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[10rem] 2xl:ml-[9.7rem] xl:ml-[6.5rem]">01</h2>
              </div>
            </div>
            <div className="bg-[#000000BA]   ">

              <h1 className="text-xl text-white font-light text-center pt-10">Personalized Learning Paths</h1>
              <p className="text-left text-white lg:m-4 text-sm">No two learners are the same — so why should your learning journey be?
                After your skill analysis, MockMingle creates a custom roadmap for your improvement.
                Follow guided steps with learning milestones, progress reports, and recommended exercises to close your skill gaps faster.
              </p>

              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10.6rem] xl:ml-[6.5rem]  ml-[10rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[10.5rem] 2xl:ml-[11.1rem] xl:ml-[7rem]">02</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">Company & College Integration</h1>
                <p className="text-left text-white lg:m-4 text-sm">MockMingle fits seamlessly into corporate and academic environments.
                  Whether you’re a student aiming to impress recruiters or an employee wanting to upgrade your skills, your performance reports are easy to share with colleges, training departments, or potential employers.</p>
              </div>

              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10.6rem] xl:ml-[6.5rem]  ml-[10rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[10.5rem] 2xl:ml-[11.1rem] xl:ml-[7rem]">03</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">RealMock Interview – Practice it to perfection!</h1>
                <p className="text-left lg:m-4 text-white text-sm">Get some real-world interviews under your belt before the real deal.
                  MockMingle doesn't just provide you theories — it puts you in realistic time-bound mocks according to your desired job role or domain. Prepare with the industry-standard questions, behavioral assessments, and technical rounds — that way, you’re not just prepared, you’re practiced.</p>
              </div>
            </div>

          </div>

          {/* Card 3 */}
          <div>
            <div className="flex mt-28 justify-center flex-col bg-gradient-to-t from-[#000000] to-[#D4D4D4] rounded-t-lg p-4">
              <div className="relative m-auto -mt-28 w-48 h-48 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                <div className="w-40 h-40 flex items-center justify-center bg-white bg-opacity-50 rounded-full shadow-inner">
                  <div className="w-32 h-32 flex items-center justify-center bg-[#9d77a6] rounded-full shadow-inner">
                    <Image src="/intractive.svg" alt="Interactive" width={64} height={64} className=" min-w-[55rem] min-h-[55rem] -ml-[1rem] mt-[3.9rem]" />
                  </div>
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white mt-10 text-center " style={{
                  fontFamily: "Arial, sans-serif",
                  textShadow: "2px 2px 3px rgba(255, 255, 255, 0.5)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                }}>Interactive</h1>
              </div>
              <div className="mt-10 mr-14 ">
                <div className="absolute  mt-3 ml-[8.5rem] lg:ml-[6rem] 2xl:ml-[9rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[9rem] lg:ml-[6.5rem] 2xl:ml-[9.5rem]">01</h2>
              </div>
            </div>

            <div className="bg-[#000000BA]  ">

              <h1 className="text-xl font-light text-white text-center pt-10">Gamified Challenges</h1>
              <p className="text-left lg:m-4 text-white text-sm">Learning meets excitement at MockMingle!
                Daily and weekly challenges across different skill sets help you practice consistently.
                Win rewards, unlock achievements, and see yourself climb the leaderboard — making preparation fun, addictive, and goal-oriented.
              </p>

              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10.6rem] xl:ml-[6.5rem]  ml-[10rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[10.5rem] 2xl:ml-[11.1rem] xl:ml-[7rem]">02</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">Leaderboards and Achievements</h1>
                <p className="text-left lg:m-4 text-white text-sm">Compete, win, and celebrate your growth!
                  Every task, chat session, interview, and challenge earns you points.
                  Get ranked on leaderboards, earn achievement badges, and unlock exclusive rewards — keeping you motivated throughout your journey.</p>
              </div>

              <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />
              <div className="-mt-[2.9rem] ">
                <div className="absolute mt-3 2xl:ml-[10.6rem] xl:ml-[6.5rem]  ml-[10rem] w-[6rem] h-[3rem] overflow-hidden">
                  <div className="w-[2.5rem] h-[1.5rem] bg-[#6a6969bb] rounded-b-full opacity-100" />
                </div>

                <h2 className="absolute rounded-full w-[1.5rem] h-[1.5rem] bg-white border-[1px] border-gray-500 text-sm  text-center mt-[0.3rem] ml-[10.5rem] 2xl:ml-[11.1rem] xl:ml-[7rem]">03</h2>
              </div>
              <div className="text-center mt-20">
                <h1 className="text-xl font-light text-white text-center pt-10">Role-Based Scenerios & Adaptive Q&A</h1>
                <p className="text-left lg:m-4 text-white pb-7 text-sm">Rehearse for your dream role, not for just any role at all.
                  MockMingle also will modify each session depending on your desired job title or industry — whether it’s software development, marketing, finance or HR. Receive scenario-based questions, case studies, and role-specific challenges that emulate a real-world interview. The more you practice, the smarter the platform gets at personalizing your experience.</p>
              </div>
            </div>
          </div>
        </div>
        <div>

          <h2 className="text-5xl font-bold mt-10 ">Simple, Transparent Pricing</h2>
          <p className=" mt-10 text-3xl  font-semibold">Pay only for what you use. No hidden fees, no contracts, no surprises. Our pricing is simple and transparent, making it easy to budget and plan your learning journey.</p>
        </div>


        <div className="grid mt-10 grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
      {plans.map((plan, index) => (
        <div
          key={index}
          onClick={() => setSelected(index)}
          className={`cursor-pointer rounded-xl bg-black  shadow-lg transition-all duration-300 border-2 ${
            selected === index ? 'border-blue-500 scale-105' : 'border-transparent'
          }`}
        >
          {/* Plan Header */}
          <div className={`p-8 -mt-[0.2rem] rounded-t-[55rem] rounded-b-full text-center ${
            index === 0 ? 'bg-[#86717A] text-white ' : 'bg-[#86717A]'
          }`}>
            <h2 className="text-xl font-bold">{plan.title}</h2>
            <h3 className="text-lg font-semibold mt-2">₹ {plan.price}</h3>
          </div>

          {/* Features */}
          <div className={`p-4 ${index === 0 ? 'bg-black text-white' : 'bg-black text-white'} rounded-b-xl`}>
            <ul className="space-y-1 text-sm font-medium">
              {features.map((feature, i) => (
                <li key={i}>{feature}</li>
              ))}
            </ul>
          </div>
        </div>
      ))}
    </div>
        </div>
        <footer className="bg-black h-[17rem] overflow-y-hidden overflow-x-hidden">

          <div className="grid grid-cols-2 ">
            <div>
            <img src="/SVG_mascote.svg" alt="" className="h-[70rem] -mt-[23rem] -mb-[15rem] -pb-[10rem] w-[auto]" />
            </div>
            <div className="    ">
<h1 className="bg-white rounded-full text-center w-32 mt-5 m-auto">Contact Us</h1>
<h2
          className="text-2xl lg:text-2xl text-center font-bold  py-4 text-white"
          style={{
            fontFamily: "Arial, sans-serif",
            backgroundColor: "white",
            color: "transparent",
            textShadow: "2px 2px 3px rgba(0, 0, 0, 0.7)",
            WebkitBackgroundClip: "text",
            backgroundClip: "text",
          }}
        >
          info@shakktii.in
        </h2>
        <div className="flex justify-around mt-20">

<h2 className="text-white border-2 p-2 rounded-full">Terms & Conditions</h2>
<h2 className="text-white border-2 p-2 rounded-full">Privacy Policy</h2>
        </div>

            </div>
          </div>
        </footer>

      </>
      );
}