


// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import { getApiResponse } from './api/response';
// import Link from "next/link";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage

//   useEffect(() => {
//     // Request microphone (audio) access
//     const requestPermissions = async () => {
//       try {
//         // Requesting audio permission (microphone)
//         await navigator.mediaDevices.getUserMedia({ audio: true, sound: true });
//         console.log("Microphone and sound access granted.");
//       } catch (err) {
//         console.error("Microphone and sound access denied:", err);
//         // Optionally, show an alert or message to the user about the permission issue
//       }
//     };

//     requestPermissions();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, []);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (<><Head>
//     <title>Shakktii Interview Trainer</title>
//     <meta name="description" content="Generated by create next app" />
//     <meta name="viewport" content="width=device-width, initial-scale=1" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//     <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//       {/* Navigation Bar */}
//       <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//         <div className="text-white text-lg font-bold">Shaktti AI</div>
//         <ul className="flex space-x-6 text-sm">
//           <li className="hover:text-purple-400 cursor-pointer">Home</li>
//           <Link href={'/oldreport'}>
//             <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//               Reports
//               {/* Show the notification red dot if true */}
//               {notification && (
//                 <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//               )}
//             </li>
//           </Link>
//           <div className="relative">
//             {/* User Dropdown */}
//             {user?.value && (
//               <div className="relative">
//                 <MdAccountCircle
//                   className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                   onClick={toggleDropdown} // Toggle on click
//                 />
//                 {dropdown && (
//                   <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                     <ul>
//                       {/* Profile Link */}
//                       <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                         Profile
//                       </li></Link>
//                       {/* Logout Link */}
//                       <li
//                         onClick={Logout}
//                         className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                       >
//                         Logout
//                       </li>
//                     </ul>
//                   </div>
//                 )}
//               </div>
//             )}

//             {/* Login button for guests */}
//             {!user?.value && (
//               <Link href="/login">
//                 <div className="ml-4">
//                   <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                     Login
//                   </button>
//                 </div>
//               </Link>
//             )}
//           </div>
//         </ul>
//       </nav>

//       {/* Header Section */}
//       <div className="flex flex-col items-center text-center">
//         {/* Logo */}
//         <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//           <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//         </div>

//         <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//         <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//         {/* Image Section */}
//         <div className="flex justify-center mt-4 mb-4">
//           <img
//             src="/home.png"
//             alt="Job Interview"
//             className="max-w-sm w-full h-auto object-contain"
//           />
//         </div>

//         {/* Description */}
//         <p className="text-center text-gray-300 max-w-lg mx-auto">
//           Landing your dream job starts with a great interview. We provide expert tips, real-world
//           insights, and proven strategies to help you impress employers and stand out from the
//           competition.
//         </p>

//         {/* List of Services */}
//         <ul className="mt-4 text-center space-y-2 text-gray-200">
//           <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//           <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//           <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//         </ul>

//         {/* Call to Action Button */}
//         <div className="mt-6 flex justify-center pb-10">
//           <Link href={'/role'}>
//             <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
//               GET STARTED
//             </button>
//           </Link>
//         </div>
//       </div>
//     </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = false;
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   // Start the speech recognition when the component mounts or when the user clicks a button
//   const startRecognition = () => {
//     if (recognition.current) {
//       recognition.current.start(); // Start listening to the user's speech
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Call to Action Button */}
//           <div className="mt-6 flex justify-center pb-10">
//             {/* Replacing the button with speech recognition trigger */}
//             {!speechRecognizing && (
//               <button
//                 onClick={startRecognition}
//                 className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600"
//               >
//                 Speak "I am ready" to Get Started
//               </button>
//             )}
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// import { useState, useEffect, useRef } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import { useRouter } from 'next/router'; // For programmatic navigation
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const [isStored, setIsStored] = useState(false); // To track if the item is successfully stored in localStorage
//   const [speechRecognizing, setSpeechRecognizing] = useState(false); // State to track speech recognition status
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//           setSpeechRecognizing(true);
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           setSpeechRecognizing(false);
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }


// import { useState, useEffect, useRef } from "react";
// import Link from "next/link";
// import Head from "next/head";
// import { IoIosArrowBack } from "react-icons/io";
// import { MdAccountCircle } from 'react-icons/md';
// import { useRouter } from 'next/router'; // For programmatic navigation

// export default function Home({ Logout, user }) {
//   const [dropdown, setDropdown] = useState(false);
//   const [notification, setNotification] = useState(false); // State to track the notification
//   const router = useRouter(); // Next.js router to navigate to /role

//   const recognition = useRef(null); // Reference to the speech recognition instance

//   useEffect(() => {
//     // Initialize Speech Recognition API
//     const initSpeechRecognition = () => {
//       if (window.SpeechRecognition || window.webkitSpeechRecognition) {
//         recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
//         recognition.current.lang = "en-US";
//         recognition.current.continuous = true; // Continuous recognition
//         recognition.current.interimResults = false;

//         recognition.current.onstart = () => {
//           console.log("Speech recognition started.");
//         };

//         recognition.current.onend = () => {
//           console.log("Speech recognition ended.");
//           if(!recognition.current.onstart){

//         }
//           // You can try to restart recognition only if it's completely ended.
//           // No need to call start() here if it's already restarted before
//         };

//         recognition.current.onresult = (event) => {
//           const transcript = event.results[0][0].transcript.toLowerCase();
//           console.log("Transcript: ", transcript);

//           if (transcript.includes("i am ready")) {
//             router.push("/role"); // Redirect to /role when "I am ready" is spoken
//           }
//         };

//         // Start listening when the page loads
//         recognition.current.start();
//       } else {
//         console.error("Speech recognition is not supported in this browser.");
//       }
//     };

//     initSpeechRecognition();

//     // Check if there’s a notification stored in localStorage when the component mounts
//     const checkStorage = () => {
//       const storedNotification = localStorage.getItem("store");
//       if (storedNotification) {
//         setNotification(true);
//       }
//     };

//     checkStorage();
//   }, [router]);

//   const toggleDropdown = () => setDropdown(prev => !prev);

//   // Function to simulate storing an item in localStorage and triggering the notification
//   const handleReportClick = () => {
//     localStorage.removeItem("store"); // Remove notification from localStorage
//     setNotification(false); // Hide the notification dot
//   };

//   return (
//     <>
//       <Head>
//         <title>Shakktii Interview Trainer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
//         {/* Navigation Bar */}
//         <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
//           <div className="text-white text-lg font-bold">Shaktti AI</div>
//           <ul className="flex space-x-6 text-sm">
//             <li className="hover:text-purple-400 cursor-pointer">Home</li>
//             <Link href={'/oldreport'}>
//               <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
//                 Reports
//                 {/* Show the notification red dot if true */}
//                 {notification && (
//                   <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
//                 )}
//               </li>
//             </Link>
//             <div className="relative">
//               {/* User Dropdown */}
//               {user?.value && (
//                 <div className="relative">
//                   <MdAccountCircle
//                     className="text-2xl md:text-3xl mx-2 cursor-pointer"
//                     onClick={toggleDropdown} // Toggle on click
//                   />
//                   {dropdown && (
//                     <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
//                       <ul>
//                         {/* Profile Link */}
//                         <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
//                           Profile
//                         </li></Link>
//                         {/* Logout Link */}
//                         <li
//                           onClick={Logout}
//                           className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
//                         >
//                           Logout
//                         </li>
//                       </ul>
//                     </div>
//                   )}
//                 </div>
//               )}

//               {/* Login button for guests */}
//               {!user?.value && (
//                 <Link href="/login">
//                   <div className="ml-4">
//                     <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
//                       Login
//                     </button>
//                   </div>
//                 </Link>
//               )}
//             </div>
//           </ul>
//         </nav>

//         {/* Header Section */}
//         <div className="flex flex-col items-center text-center">
//           {/* Logo */}
//           <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
//             <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
//           </div>

//           <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
//           <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

//           {/* Image Section */}
//           <div className="flex justify-center mt-4 mb-4">
//             <img
//               src="/home.png"
//               alt="Job Interview"
//               className="max-w-sm w-full h-auto object-contain"
//             />
//           </div>

//           {/* Description */}
//           <p className="text-center text-gray-300 max-w-lg mx-auto">
//             Landing your dream job starts with a great interview. We provide expert tips, real-world
//             insights, and proven strategies to help you impress employers and stand out from the
//             competition.
//           </p>

//           {/* List of Services */}
//           <ul className="mt-4 text-center space-y-2 text-gray-200">
//             <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
//             <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
//             <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
//           </ul>

//           {/* Informational text about speech recognition */}
//           <div className="mt-6 flex justify-center pb-10">
//             <p className="text-lg font-semibold text-gray-200">
//               Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }



import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import { IoIosArrowBack } from "react-icons/io";
import { MdAccountCircle } from 'react-icons/md';
import { useRouter } from 'next/router'; // For programmatic navigation



export default function Home({ Logout, user }) {
  const [dropdown, setDropdown] = useState(false);
  const [notification, setNotification] = useState(false); // State to track the notification
  const router = useRouter(); // Next.js router to navigate to /role
  const recognition = useRef(null); // Reference to the speech recognition instance
  const [isRecognizing, setIsRecognizing] = useState(false); // To track whether recognition is ongoing

  useEffect(() => {
    // Initialize Speech Recognition API
    const initSpeechRecognition = () => {
      if (window.SpeechRecognition || window.webkitSpeechRecognition) {
        recognition.current = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
        recognition.current.lang = "en-US";
        recognition.current.continuous = true; // Continuous recognition
        recognition.current.interimResults = false;

        recognition.current.onstart = () => {
          console.log("Speech recognition started.");
          setIsRecognizing(true); // Set the recognizing flag to true
        };

        recognition.current.onend = () => {
          console.log("Speech recognition ended.");
          setIsRecognizing(false); // Set the recognizing flag to false

          // Restart recognition only if it's fully ended and not already recognizing
          if (recognition.current && !isRecognizing && recognition.current.state === "inactive") {
            console.log("Speech recognition restarted."); // Debug log
            recognition.current.start(); // Restart recognition
          }
        };

        recognition.current.onresult = (event) => {
          const transcript = event.results[0][0].transcript.toLowerCase();
          console.log("Transcript: ", transcript);

          // If the user says "I am ready", navigate to /role
          if (transcript.includes("i am ready")) {
            router.push("/role"); // Redirect to /role when "I am ready" is spoken
          }
        };

        // Start listening when the page loads if it's not already started
        if (recognition.current && !isRecognizing) {
          recognition.current.start();
        }
      } else {
        console.error("Speech recognition is not supported in this browser.");
      }
    };

    initSpeechRecognition();

    // Check if there’s a notification stored in localStorage when the component mounts
    const checkStorage = () => {
      const storedNotification = localStorage.getItem("store");
      if (storedNotification) {
        setNotification(true);
      }
    };

    checkStorage();
  }, [router, isRecognizing]);

  const toggleDropdown = () => setDropdown(prev => !prev);

  // Function to simulate storing an item in localStorage and triggering the notification
  const handleReportClick = () => {
    localStorage.removeItem("store"); // Remove notification from localStorage
    setNotification(false); // Hide the notification dot
  };

  return (
    <>
      <Head>
        <title>Shakktii Interview Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-gradient-to-b text-white px-4 bg-cover flex flex-col items-center justify-center" style={{ backgroundImage: "url('/bg.gif')" }}>
        {/* Navigation Bar */}
        <nav className="flex justify-between items-center py-4 px-6 bg-black bg-opacity-50 w-full">
          <div className="text-white text-lg font-bold">Shaktti AI</div>
          <ul className="flex space-x-6 text-sm">
            <li className="hover:text-purple-400 cursor-pointer">Home</li>
            <Link href={'/oldreport'}>
              <li className="relative hover:text-purple-400 cursor-pointer" onClick={handleReportClick}>
                Reports
                {/* Show the notification red dot if true */}
                {notification && (
                  <span className="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-2.5 h-2.5"></span>
                )}
              </li>
            </Link>
            <div className="relative">
              {/* User Dropdown */}
              {user?.value && (
                <div className="relative">
                  <MdAccountCircle
                    className="text-2xl md:text-3xl mx-2 cursor-pointer"
                    onClick={toggleDropdown} // Toggle on click
                  />
                  {dropdown && (
                    <div className="absolute right-0 shadow-xl top-10 rounded-md w-40 border-2 border-solid border-gray-300">
                      <ul>
                        {/* Profile Link */}
                        <Link href={'/profile'}><li className="hover:text-blue-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100">
                          Profile
                        </li></Link>
                        {/* Logout Link */}
                        <li
                          onClick={Logout}
                          className="hover:text-red-700 text-sm font-bold p-3 cursor-pointer border-b-2 border-solid border-gray-300 hover:bg-gray-100"
                        >
                          Logout
                        </li>
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {/* Login button for guests */}
              {!user?.value && (
                <Link href="/login">
                  <div className="ml-4">
                    <button className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition ease-in-out duration-200">
                      Login
                    </button>
                  </div>
                </Link>
              )}
            </div>
          </ul>
        </nav>

        {/* Header Section */}
        <div className="flex flex-col items-center text-center">
          {/* Logo */}
          <div className="w-20 h-20 mt-5 border-2 border-white rounded-full flex items-center justify-center">
            <img src="/Logo.png" alt="Logo" className="w-16 h-16 object-contain" />
          </div>

          <h1 className="text-4xl font-bold mt-4 text-pink-400">Job</h1>
          <h2 className="text-3xl font-bold text-pink-500">Interview</h2>

          {/* Image Section */}
          <div className="flex justify-center mt-4 mb-4">
            <img
              src="/home.png"
              alt="Job Interview"
              className="max-w-sm w-full h-auto object-contain"
            />
          </div>

          {/* Description */}
          <p className="text-center text-gray-300 max-w-lg mx-auto">
            Landing your dream job starts with a great interview. We provide expert tips, real-world
            insights, and proven strategies to help you impress employers and stand out from the
            competition.
          </p>

          {/* List of Services */}
          <ul className="mt-4 text-center space-y-2 text-gray-200">
            <li>✅ <span className="text-pink-400">Interview Preparation</span> - Master common questions.</li>
            <li>✅ <span className="text-pink-400">Resume & Cover Letter Tips</span> - Showcase your skills.</li>
            <li>✅ <span className="text-pink-400">Career Coaching</span> - Get expert guidance.</li>
          </ul>

          {/* Informational text about speech recognition */}
          <div className="mt-6 flex justify-center pb-10">
            <p className="text-lg font-semibold text-gray-200">
              Please speak the phrase <span className="text-pink-500">"I am ready"</span> to proceed.
            </p>
          </div>
          Speak OR Click On Get Started
          <div className="mt-6 flex justify-center pb-10">
            <Link href={'/role'}>
              <button className="bg-pink-500 text-white py-3 px-6 rounded-lg text-lg font-semibold hover:bg-pink-600">
                GET STARTED
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
